POST http://localhost:3003/api/register
Content-Type: application/json

{
"username": "liika",
"password": "salasana",
"role": 0,
"email": "Liika2025@outlook.com",
"location": {
"lat": 62.6000,
"lng": 29.7639
}
}