export const categories = {
  1: { visible: true, markers: [] },
  2: { visible: true, markers: [] },
  3: { visible: true, markers: [] },
  4: { visible: true, markers: [] },
  5: { visible: true, markers: [] },
  6: { visible: true, markers: [] },
  7: { visible: true, markers: [] },
  8: { visible: true, markers: [] },
  9: { visible: true, markers: [] },
  10: { visible: true, markers: [] },
  11: { visible: true, markers: [] },
  12: { visible: true, markers: [] },
  13: { visible: true, markers: [] },
  14: { visible: true, markers: [] },
  15: { visible: true, markers: [] },
  16: { visible: true, markers: [] },
  17: { visible: true, markers: [] },
  18: { visible: true, markers: [] },
  19: { visible: true, markers: [] },
  20: { visible: true, markers: [] },
}
