const { up: upCategories, down: downCategories } = require("./categories")
const { up: upClubs, down: downClubs } = require("./clubs")
const { up: upUsers, down: downUsers } = require("./users")
const { up: upClubmembers, down: downClubmembers } = require("./clubMember")
const { up: upEvents, down: downEvents } = require("./events")
const { up: upJoins, down: downJoins } = require("./joins")
const { up: upLanguages, down: downLanguages } = require("./languages")
const { up: upTimes, down: downTimes } = require("./times")
const { sequelize } = require("../utils/database")
const { queryInterface } = require("../utils/database")

module.exports = resetDB = async () => {
  await downCategories(queryInterface, sequelize)
    .then(() => downClubs(queryInterface, sequelize))
    .then(() => downUsers(queryInterface, sequelize))
    .then(() => downClubmembers(queryInterface, sequelize))
    .then(() => downEvents(queryInterface, sequelize))
    .then(() => downJoins(queryInterface, sequelize))
    .then(() => downLanguages(queryInterface, sequelize))
    .then(() => downTimes(queryInterface, sequelize))
    .then(() => upLanguages(queryInterface, sequelize))
    .then(() => upUsers(queryInterface, sequelize))
    .then(() => upCategories(queryInterface, sequelize))
    .then(() => upClubs(queryInterface, sequelize))
    .then(() => upClubmembers(queryInterface, sequelize))
    .then(() => upEvents(queryInterface, sequelize))
    .then(() => upTimes(queryInterface, sequelize))
    .then(() => upJoins(queryInterface, sequelize))
}
